// Falk AdSolution - Copyright (c) 2004 by Falk eSolutions AG - All rights reserved (Build: 00000070)
Ads_Build='00000070';var QQbA,QQcA,QQdA,QQeA,QQfA,QQgA,QQhA,QQiA,QQjA,QQkA,QQlA,QQmA,QQnA,QQoA,QQpA;NUM_FARM=1;QQbA=['http://a.as-test.falkag.net' ,'http://a.as-eu.falkag.net' ,'http://a.ads.t-online.de' ,'http://a.as-us.falkag.net' ,'http://a.as-rh4.falkag.net' ,'','','','',''];QQcA=['http://a.as-test.falkag.net' ,'https://s.as-eu.falkag.net' ,'https://s.ads.t-online.de' ,'https://s.as-us.falkag.net' ,'http://a.as-rh4.falkag.net' ,'','','','',''];QQdA=['http://a.as-test.falkag.net' ,'http://a.as-eu.falkag.net' ,'http://a.ads.t-online.de' ,'http://a.as-us.falkag.net' ,'http://a.as-rh4.falkag.net' ,'','','','',''];QQeA=['http://a.as-test.falkag.net' ,'https://s.as-eu.falkag.net' ,'https://s.ads.t-online.de' ,'https://s.as-us.falkag.net' ,'http://a.as-rh4.falkag.net' ,'','','','',''];QQfA=['http://bw.as-test.falkag.net' ,'http://bw.as-eu.falkag.net' ,'http://bw.ads.t-online.de' ,'http://bw.as-us.falkag.net' ,'http://a.as-rh4.falkag.net' ,'','','','',''];QQgA=['http://bw.as-test.falkag.net' ,'https://s.as-eu.falkag.net' ,'https://s.ads.t-online.de' ,'https://s.as-us.falkag.net' ,'http://a.as-rh4.falkag.net' ,'','','','',''];QQhA=['http://red.as-test.falkag.net' ,'http://red.as-eu.falkag.net' ,'http://red.ads.t-online.de' ,'http://red.as-us.falkag.net' ,'http://red.as-rh4.falkag.net' ,'','','','',''];QQiA=['http://red.as-test.falkag.net' ,'https://red.as-eu.falkag.net' ,'https://red.ads.t-online.de' ,'https://s.as-us.falkag.net' ,'http://red.as-rh4.falkag.net' ,'','','','',''];QQjA=['http://sel.as-test.falkag.net/server/asldata.js','http://data.as-eu.falkag.net/server/asldata.js','http://data.ads.t-online.de/server/asldata.js' ,'http://data.as-us.falkag.net/server/asldata.js' ,'http://a.as-rh4.falkag.net/server/asldata.js','','','','',''];QQkA=['http://sel.as-test.falkag.net/server/asldata.js','https://as1.falkag.de/server/asldata.js' ,'https://red.ads.t-online.de/server/asldata.js' ,'https://s.as-us.falkag.net/server/asldata.js' ,'http://a.as-rh4.falkag.net/server/asldata.js','','','','',''];QQlA=['.as-test.falkag.net' ,'.as-eu.falkag.net' ,'.ads.t-online.de' ,'.as-us.falkag.net' ,'.as-rh4.falkag.net' ,'','','','',''];QQmA=['Falk AdSolution' ,'AdSolution' ,'Adsolution' ,'Falk AdSolution' ,'Falk AdSolution RH4' ,'','','','',''];QQnA=['/dat/bgf/trpix.gif?' ,'/dat/bgf/trpix.gif?' ,'/dat/bgf/trpix.gif?' ,'/dat/bgf/trpix.gif?' ,'/dat/bgf/trpix.gif?' ,'','','','',''];QQoA=['/red?cmd=red&' ,'/red?cmd=red&' ,'/red?cmd=red&' ,'/red?cmd=red&' ,'/red?cmd=red&' ,'','','','',''];QQpA=['/red?cmd=url&' ,'/red?cmd=url&' ,'/red?cmd=url&' ,'/red?cmd=url&' ,'/red?cmd=url&' ,'','','','',''];// Falk AdSolution - Copyright (c) 2004 by Falk eSolutions AG - All rights reserved (Build: 00000070)
function QQbD(QQTb)
{document.write('<scr'+'ipt type="text/javascript" language="JavaScript" src="'+QQTb+'"></scr'+'ipt>');}function QQcD(QQUb)
{var QQVb=this.location.hostname.toLowerCase();var QQWb='';var QQXb=QQVb;var QQYb=[];intPos1=QQVb.indexOf('.');if (QQUb==1)
{if (intPos1!=-1)
{while (intPos1!=-1)
{intPos1=QQXb.indexOf('.');QQYb[QQYb.length]=(intPos1==-1)?QQXb.substring(intPos1+1,QQXb.length):QQXb.substring(0,intPos1);QQXb=QQXb.substring(intPos1+1,QQXb.length);}if (QQYb[QQYb.length-2]=='falkag')
{for (var intI=1;intI<QQYb.length;intI++)
{QQl=QQYb.length-intI;QQWb=QQYb[QQl]+((QQWb=='')?'':'.'+QQWb);}}else
{QQWb=(QQYb[QQYb.length-2].length<3)?QQVb:QQYb[QQYb.length-2]+'.'+QQYb[QQYb.length-1];}}}else
{if (intPos1==-1)
{QQWb='';}else
{if((intPos1>=0)&&(intPos1<QQVb.length))
{intPos2=QQVb.indexOf('.',intPos1+1);if(intPos2>intPos1)
QQWb=QQVb.substring(intPos1+1,QQVb.length);}if ((QQWb.lastIndexOf('.')==QQWb.indexOf('.'))&&QQWb.lastIndexOf('.')<3)
QQWb=QQVb;}}return QQWb;}function QQdD()
{var QQWb=QQcD(0);if(QQWb=='')
return 'D'+this.location.hostname;else
return 'D'+QQWb;}function QQeD(QQZb)
{var QQWb=QQcD(0);if(QQZb==-1)
{	 if(QQWb!='')
	 QQWb=' domain='+QQWb;	return ';path=/;'+QQWb;}var QQAc=new Date();if(QQWb!='')
QQWb=';domain='+QQWb;QQAc.setTime(parseInt(QQAc.getTime(),10)+1000*60*parseInt(QQZb,10));return ';path=/;expires='+QQAc.toGMTString()+QQWb;}function QQfD(QQZb)
{var QQWb=QQcD(1);if(QQZb==-1)
{	 if(QQWb!='')
	 QQWb=' domain='+QQWb;	return ';path=/;'+QQWb;}var QQAc=new Date();if(QQWb!='')
QQWb=';domain='+QQWb;QQAc.setTime(parseInt(QQAc.getTime(),10)+1000*60*parseInt(QQZb,10));return ';path=/;expires='+QQAc.toGMTString()+QQWb;}function QQgD(QQc,QQd,QQy)
{if(QQsA!=-1) var intBwdTyp=KAS[QQsA][4][27];if(typeof(intBwdTyp)=='undefined')
intBwdTyp=0;var QQz=[];QQz[0]='&dlv='+Ads_nid+','+Ads_wid+','+Ads_iid+','+QQc+','+QQd+'&kid='+QQc+QQy[0]+((QQyC( Ads_iid,QQc )&&(QQvB>0))?QQtB:'');QQz[1]='&dlv='+Ads_nid+','+Ads_wid+','+Ads_iid+','+QQc+','+QQd+'&kid='+QQc+'&chw='+QQqA+'&tcs='+QQrA+QQy[1]+((QQyC( Ads_iid,QQc )&&(QQvB>0))?QQtB:'')+QQvA;var QQBc='&sta=';QQz[0]+='&dmn='+Ads_T[5];QQz[1]+='&dmn='+Ads_T[5];if(navigator.appVersion.substring(0,1)>'3')
{QQz[0]+='&scx='+screen.width+'&scy='+screen.height+'&scc='+screen.colorDepth;QQz[1]+='&scx='+screen.width+'&scy='+screen.height+'&scc='+screen.colorDepth;QQBc+=',,,'+(navigator.javaEnabled()?'1':'0');if(navigator.javaEnabled())
QQz[1]+='&jav=1';}else
QQBc+=',,,';var QQCc=new Date();QQBc+=',,,,,,';if((Ads_wrd!='')&&(Ads_wrd.toLowerCase()!='[keyword]'))
{var QQDc='!"%&\'()*+#-./:;<=>?@[\\]^{|}~§ ';var QQEc,QQFc='';for(QQl=0;QQl<Ads_wrd.length;QQl++)
{QQEc=Ads_wrd.charAt(QQl);if(QQDc.indexOf(QQEc)!=-1)
QQEc=',';QQFc+=QQEc;}QQFc =QQFc.toLowerCase();QQz[0]+='&wrd='+QQFc;QQz[1]+='&wrd='+QQFc;Ads_wrd=QQFc;QQBc+='';}QQBc+=','+QQwE[10]+','+Ads_T[13]+','+intBwdTyp+','+Ads_T[4]+','+Ads_T[10]+','+Ads_T[11]+','+Ads_T[3]+','+Ads_T[12];QQz[0]+=QQBc;QQz[1]+=QQBc;if(gbolSUXX25067) QQz[1]+='&trglog='+escape(gstrXarrTargetDaten);QQz[0]=Ads_Timestamp+QQz[0];QQz[1]=Ads_Timestamp+QQz[1];QQz[2]=QQz[1]+QQy[0];return (QQz);}function QQhD(QQc,QQd,QQy)
{var QQGc=[];var QQHc=[];QQHc=QQgD(QQc,QQd,QQy);QQGc[0] ='&rdm='+QQHc[0]+'&iid='+Ads_iid+'&bid='+QQd;QQGc[1] ='&rdm='+QQHc[1]+'&iid='+Ads_iid+'&bid='+QQd;return QQGc;}function QQiD()
{if (typeof(QQgB[Ads_sec])=='undefined')
QQuC();return QQgB[Ads_sec]+(QQyA?QQoA[NUM_FARM]+'flg='+QQxC()+'&dat='+QQfB[Ads_sec]+'/dat/bgf/trpix.gif&':QQnA[NUM_FARM]);}function QQjD()
{return QQgB[Ads_sec]+QQnA[NUM_FARM]+'cmd=req&';}function QQkD(QQIc,QQb)
{if (QQIc==0)
{QQpD(1,'',QQiD()+QQb);return ((Ads_opt&512)>0)?'':(QQtD('Ads_Count'+Ads_iid)+'<img src="'+QQiD()+QQb+'" width="1" height="1">'+QQuD());}else if (QQIc==1)
{QQpD(1,'Request tracking URL',QQjD()+QQb);return QQtD('Ads_ReqCount'+Ads_iid)+'<img src="'+QQjD()+QQb+'" width="1" height="1">'+QQuD();}}function QQlD(QQt,QQb)
{QQt.document.write(QQkD(0,QQb));}function QQmD()
{return QQnD(Math.random()*100000000,8);}function QQnD(QQJc,QQKc)
{var QQLc='#'+(QQJc+100000000);return QQLc.substr(10-QQKc,QQKc);}function QQoD(QQFc,QQMc,QQNc)
{var QQl;while((QQl=QQFc.indexOf(QQMc))!=-1)
QQFc=QQFc.substr(0,QQl)+QQNc+QQFc.substring(QQl+QQMc.length,QQFc.length);return QQFc;}function QQpD(QQE,QQFc,QQOc)
{var QQPc=new Date();if(Ads_debug==1)
{document.write(((QQE!=3)?'':'<br>')+'<font color=#0000ff>[DEBUG'+((QQPc-QQwA)/1000)+']</font> ');if((QQE==0)||(QQE==3))
document.write('<b><big>'+QQFc+'</big></b><br>');else if(QQE==1)
document.write(''+QQFc+': &nbsp;<font color=#000080>'+QQOc+'</font><br>');else
document.write('<b>'+QQFc+'</b><br>');}else if((Ads_debug==2)&&(QQE==3))
document.write('<font color=#0000ff>[DEBUG'+((QQPc-QQwA)/1000)+']</font> <b><big>'+QQFc+'</big></b><br>');}function QQqD(QQCb)
{var QQD='#'+(parseInt(QQCb,10)+100000000);return QQD.substr(2,2)+'/'+QQD.substr(4,2)+'/'+QQD.substr(6,2)+'/'+QQD.substr(8,2);}function QQrD(QQJc)
{var QQQc='0123456789ABCDEF';var QQRc='';while(QQJc>0)
{QQRc=QQQc.substr(QQJc%16,1)+QQRc;QQJc=parseInt(QQJc/16,10);}return (QQRc=='')?'0':QQRc;}function QQsD(QQMa)
{var QQSc;var QQTc=0;if(QQaB>-1)
{QQTc=QQaB;return QQTc;}if((QQMa==0)&&((Ads_opt&2048)>0))
return -1;if((navigator.userAgent.indexOf("Opera")!=-1)||((navigator.appName=="Netscape")&&(navigator.userAgent.indexOf("Mozilla")!=-1)&&(parseFloat(navigator.appVersion)>=4)))
{if(navigator.mimeTypes&&navigator.mimeTypes["application/x-shockwave-flash"]&&navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin)
{QQSc=navigator.plugins['Shockwave Flash'].description;QQSc=QQSc.substring(QQSc.indexOf("."),-1);QQTc=QQSc.substr(-1);}}else if(navigator.userAgent&&navigator.userAgent.indexOf("MSIE")!=-1&&navigator.userAgent.indexOf("Mac")!=-1&&document.all)
{if(navigator.mimeTypes&&navigator.mimeTypes["application/x-shockwave-flash"]&&navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin)
{QQSc=navigator.plugins['Shockwave Flash'].description;QQSc=QQSc.substring(QQSc.indexOf("."),-1);QQSc=QQSc.substring(QQSc.length-1,QQSc.length);QQTc=QQSc.substr(-1);}}else if(navigator.userAgent&&navigator.userAgent.indexOf("MSIE")!=-1&&navigator.userAgent.indexOf("Windows")!=-1&&navigator.userAgent.indexOf("Windows 3")==-1&&document.all)
{document.write('<scr'+'ipt language=VBScript>\n Ads_vbCV=10\nAds_vbMV=1\nDo\nOn Error Resume Next\n');document.write('Ads_vbBF=(IsObject(CreateObject("ShockwaveFlash.ShockwaveFlash."&Ads_vbCV)))\n');document.write('If Ads_vbBF=true Then Exit Do\nAds_vbCV=Ads_vbCV-1\nLoop While Ads_vbCV>=Ads_vbMV\n </scr'+'ipt>');QQTc=Ads_vbCV;}QQaB=QQTc;return QQTc;}function QQtD(QQUc)
{if(QQrB)
return '<div id='+QQUc+' style="position:absolute;left:-1000;top:-1000;">';else
return '';}function QQuD()
{if(QQrB)
return '</div>';else
return '';}function QQvD(QQVc)
{var QQWc,QQXc;if(window.innerHeight)
{QQWc=QQVc.x;QQXc=QQVc.y;}else
{if(QQVc.offsetLeft)
{QQVc=QQVc;QQWc=QQVc.offsetLeft;QQSj=QQVc.offsetParent;while(QQSj!=null)
{QQWc+=QQSj.offsetLeft;QQSj=QQSj.offsetParent;}QQXc=QQVc.offsetTop;QQSj=QQVc.offsetParent;while(QQSj!=null)
{QQXc+=QQSj.offsetTop;QQSj=QQSj.offsetParent;}}else
return [-1000,-1000];}return [QQWc,QQXc];}function QQwD(QQYc,QQA,QQf,QQg)
{var QQZc;var QQVc=document.images[QQA];var QQAd=QQvD(QQVc);QQVc.width=QQf;QQVc.height=QQg;if(QQrB)
QQZc=document.getElementById(QQYc).style;else if(document.layers)
QQZc=document.layers[QQYc];else
QQZc=document.all[QQYc].style;QQZc.left=QQAd[0];QQZc.top=QQAd[1];if (QQrB) QQZc.display='block';else if(document.layers) QQZc.visibility='show';else QQZc.visibility='visible';}// Falk AdSolution - Copyright (c) 2004 by Falk eSolutions AG - All rights reserved (Build: 00000070)
if((typeof(Ads_debug)=='undefined')||(Ads_debug!=1))
window.onerror=QQwC;gbolSUXX25067=false;var Ads_ModulMain=true;if(typeof(Ads_ModulEffects)=='undefined')
Ads_ModulEffects=false;var QQqA,QQrA,QQsA,QQtA,QQuA,QQvA,QQwA,QQxA;var QQyA,QQzA,QQaB,QQbB,QQcB,QQdB;var QQeB=false;var QQfB=[];var QQgB=[];var QQhB=[];var QQiB=[];var QQjB=[];var QQkB=[];var QQlB=[];var QQmB=navigator.userAgent.toLowerCase();var QQnB=(QQmB.indexOf("msie")!=-1);var QQoB=((QQmB.indexOf("win")!=-1)||(QQmB.indexOf("16bit")!=-1));var QQpB=(QQmB.indexOf("mac")!=-1);var QQqB=(navigator.appName.indexOf('icrosoft')!=-1);var QQrB=(typeof(document.getElementsByTagName)!='undefined'&&typeof(document.createElement)!='undefined')?1:0;var QQsB=true;var QQtB='';var QQuB='';var QQvB=0;var QQwB=[];var QQxB=0;var QQyB=0;var QQzB=[];var QQaC;var QQbC=[];var QQcC=[];var QQdC=[];var QQeC=[];var QQfC=[];var QQgC=[];var QQhC=[];var QQiC=[];var Ads_LinkUrl,Ads_CountUrl,Ads_CountUrl_ne,Ads_ClickUrl,Ads_T,Ads_T_OW,iid,bid,rdm;var Ads_Data=[];var Ads_status=[];if(typeof(Ads_FXPL)=='undefined'){var Ads_FXPL=false;}Ads_T_OW=[];var QQjC,QQkC,Ads_gintCurVersion;var QQlC='toolbar=yes,directories=yes,status=yes,scrollbars=yes,resizable=yes,menubar=yes,location=yes';function gotoSite(){window.open(QQjC,'flashwin',QQlC);}function emosite(){window.open(QQjC,'flashwin',QQlC);}function FlashClick(){window.open(QQjC,'flashwin',QQlC);}function link1(){window.open(QQjC,'flashwin',QQlC);}function gotoURL(QQa){window.open(QQkC+escape(QQa),'flashwin',QQlC);}function QQmC()
{Ads_kid=0;Ads_bid=0;Ads_cmd='';}function QQnC(QQa)
{QQa=QQoD(QQa,'[par]',escape(Ads_par));QQa=QQoD(QQa,'[keyword]',escape(Ads_wrd));QQa=QQoD(QQa,'[timestamp]',Ads_Timestamp);if (typeof(Ads_CountUrl)!='undefined')
{QQa=QQoD(QQa,'[clickurl]',escape(Ads_CountUrl));QQa=QQoD(QQa,'[clickurl_plain]',Ads_CountUrl);QQa=QQoD(QQa,'[clickurl_double]',escape(escape(Ads_CountUrl)));QQa=QQoD(QQa,'[clickurl_ne]',escape(Ads_CountUrl.substr(0,Ads_CountUrl.length-1)+'ne='));QQa=QQoD(QQa,'[clickurl_plain_ne]',Ads_CountUrl.substr(0,Ads_CountUrl.length-1)+'ne=');QQa=QQoD(QQa,'[clickurl_double_ne]',escape(escape(Ads_CountUrl.substr(0,Ads_CountUrl.length-1)+'ne=')));}QQa=QQoD(QQa,'[web_id]',Ads_wid);QQa=QQoD(QQa,'[web_external_id]',escape(Ads_xwid));QQa=QQoD(QQa,'[con_id]',Ads_iid);QQa=QQoD(QQa,'[con_external_id]',escape(Ads_xiid));QQa=QQoD(QQa,'[ban_id]',Ads_sbid);QQa=QQoD(QQa,'[cam_id]',QQtA);return QQa;}function QQoC(QQa,QQb)
{QQpD(1,'QQoC QQb',QQb);return QQgB[Ads_sec]+QQpA[NUM_FARM]+'flg='+QQxC()+'&'+QQb+'&dat='+escape(QQa);}function QQpC(QQc,QQd,QQe,QQf,QQg)
{var QQh;if(QQvB<2)
{QQvB++;QQh=QQvB+1;QQtB+='&kid'+QQh+'='+QQc;QQtB+='&bid'+QQh+'='+QQd;QQtB+='&iid'+QQh+'='+Ads_iid;QQtB+='&dlv'+QQh+'='+Ads_nid+','+Ads_wid+','+Ads_iid+','+QQc+','+QQd;if(QQuA!=0)
QQtB+='&sid'+QQh+'='+QQuA;QQtB+='&bls3'+QQh+'='+QQuB;arrIntern=QQaD(QQe);QQxB=arrIntern[1];QQyB=arrIntern[2];Ads_iid=arrIntern[1];Ads_kid=arrIntern[2];Ads_bid=(arrIntern.length<4)?0:arrIntern[3];Ads_par=(arrIntern.length<5)?Ads_par:unescape(arrIntern[4]);Ads_xp=(arrIntern.length<6||Ads_xp!='')?Ads_xp:arrIntern[5];Ads_yp=(arrIntern.length<7||Ads_yp!='')?Ads_yp:arrIntern[6];Ads_xp1=(arrIntern.length<8||Ads_xp1!='')?Ads_xp1:arrIntern[7];Ads_yp1=(arrIntern.length<9||Ads_yp1!='')?Ads_yp1:arrIntern[8];Ads_xl=0;Ads_yl=0;QQbD(QQfB[Ads_sec]+'/dat/cjf/'+QQqD(Ads_iid)+'.js');}else
{QQtB='';QQvB=0;QQmC();}}function QQqC(QQi)
{var QQj=[];var QQk=QQi.length;var QQl;var QQm='';var QQn='';for(QQl=0;QQl<QQk;QQl+=2)
{QQm=QQi[QQl+1];if(Ads_cnturl!='')
{QQn=QQoD(Ads_cnturl,'[url]',escape(QQm));QQm=QQoD(QQn,'[url_plain]',QQm);}QQj[QQl/2+1]=Ads_CountUrl+escape(QQm)+'&bidx='+QQi[QQl];}return QQj;}function SAS()
{var QQo=false;QQuC();QQo=QQvC();if (QQo==true)
{if((document.cookie.toLowerCase().indexOf('bndlvl')==-1)&&((IAS[13]&4)>0))
QQvE();else
QQrC();}else
{QQsB=false;QQpD(1,'Waiting for asldata.','');}}function QQrC()
{var QQp;if((typeof(Ads_debug)=='undefined')||(Ads_debug!=1))
window.onerror=QQwC;if(((Ads_nid==631)||(Ads_nid==668))&&(NUM_FARM==1))
{ QQfB[0]=['http://e.as-eu.falkag.net'];QQiB[0]=QQfB[0];}if((Ads_nid==80)&&(NUM_FARM==3))
{ QQfB[0]=['http://e.as-us.falkag.net'];QQiB[0]=QQfB[0];}var QQq='undefined';for (intI=0;intI<Ads_T.length;intI++)
{if (typeof(Ads_T_OW)!=QQq)
{if (typeof(Ads_T_OW[intI])!=QQq)
{QQpD(1,'Overwriting Targeting AdsT['+intI+'] ('+Ads_T[intI]+') with',Ads_T_OW[intI]);Ads_T[intI]=Ads_T_OW[intI];}}}if(typeof(Ads_cmd)==QQq) Ads_cmd='';if(typeof(Ads_kid)==QQq) Ads_kid=0;if(typeof(Ads_bid)==QQq) Ads_bid=0;if(typeof(Ads_xl)==QQq) Ads_xl=0;if(typeof(Ads_yl)==QQq) Ads_yl=0;if(typeof(Ads_xp)==QQq) Ads_xp='';if(typeof(Ads_yp)==QQq) Ads_yp='';if(typeof(Ads_xp1)==QQq) Ads_xp1='';if(typeof(Ads_yp1)==QQq) Ads_yp1='';if(typeof(Ads_opt)==QQq) Ads_opt=0;if(typeof(Ads_wrd)==QQq) Ads_wrd='';if(typeof(Ads_prf)==QQq) Ads_prf='';if(typeof(Ads_par)==QQq) Ads_par='';if(typeof(Ads_cnturl)==QQq) Ads_cnturl='';if(typeof(Ads_ref)==QQq) Ads_ref=0;if(typeof(Ads_anc)==QQq) Ads_anc='';if(typeof(Ads_cmb)==QQq) Ads_cmb=[];if(typeof(Ads_uid)==QQq) Ads_uid='';if(typeof(Ads_bgc)==QQq) Ads_bgc='';if(typeof(Ads_status[Ads_iid])==QQq) Ads_status[Ads_iid]=[3,0,0,1];Ads_cmd=Ads_cmd.toLowerCase();if(Ads_ref==0)
Ads_ref=IAS[12];if(Ads_bgc=='')
{if(typeof(IAS[16])!=QQq)
Ads_bgc=IAS[16];}QQp=QQfB[Ads_sec]+'/dat/dlv/aslframe.html?dat='+Ads_iid +'&kid='+Ads_kid+'&wrd='+escape(Ads_wrd) +'&bid='+Ads_bid+'&prf='+escape(Ads_prf) +'&xl='+Ads_xl+'&par='+escape(Ads_par) +'&yl='+Ads_yl+'&cnturl='+Ads_cnturl+'&debug='+Ads_debug +'&xp='+Ads_xp+'&sec='+Ads_sec+'&bgc='+Ads_bgc +'&yp='+Ads_yp+'&ref='+Ads_ref +'&xp1='+Ads_xp1+'&yp1='+Ads_yp1+'&opt=';var QQr='" width="'+Ads_xl+'" height="'+Ads_yl+'" noresize scrolling="no" hspace="0" vspace="0" frameborder="0" marginheight="0" marginwidth="0"></iframe>';if(Ads_ref>0)
{document.write('<iframe src="'+QQp+Ads_opt+QQr);Ads_ref=0;return;}QQfF();if((Ads_bgc!='')&&(Ads_bgc!='-1')&&(document.body!=null))
document.body.style['backgroundColor']='#'+Ads_bgc;if(((IAS[13]&8)>0)&&(QQwE[10]==0))
QQsE();QQqA='';QQrA='';QQtA=0;QQuA=0;QQvA='';QQsA=-1;if(NUM_FARM==3)
KAS[KAS.length]=[-1,100,-1,100,[],0,0,0,0,100];if((Ads_kid==0)||(Ads_kid==''))
QQsA=QQaE();else
{QQk=KAS.length;QQsA=0;while((QQsA<QQk)&&(KAS[QQsA][0]!=Ads_kid))
QQsA++;if(QQsA==QQk)
QQsA=-1;}if((Ads_opt&256)!=0)
{if(QQsA!=-1)
{Ads_skid=KAS[QQsA][0];Ads_status[Ads_iid][0]=3;Ads_status[Ads_iid][3]=4;}else
Ads_skid=0;QQpD(1,'Skipping delivery,selected campaign:',Ads_skid);}else
{if(QQsA!=-1)
{QQtA=KAS[QQsA][0];QQuA=KAS[QQsA][6];if(QQuA!=0)
QQvA='&sid='+QQuA;Ads_status[Ads_iid][0]=(KAS[QQsA][2]==0)?2:1;Ads_status[Ads_iid][3]=3;if(QQtA>0)
{QQbD(QQfB[Ads_sec]+'/dat/bjf/'+QQqD(QQtA)+'.js');}else
DAS();}else
{QQpD(1,'no campaign selected!','');if (Ads_nid!=0)
Ads_status[Ads_iid][3]=2;DAS();}}}function DAS()
{var QQs,QQk,QQt,QQu,QQv,QQw,QQx,QQy,QQz;QQy=['',''];QQz=[];var QQA='';var QQB=['_blank','_self','_parent','_top'];var QQC=false;Ads_Timestamp=QQmD();var QQd=0;var QQD,QQf,QQg;if(IAS[9]==1)
{QQD='adsolut.gif';QQf=234;QQg=60;}else
{QQD='trpix.gif';QQf=1;QQg=1;}QQbB=QQmA[NUM_FARM];if(IAS[9]==4)
QQbB='Werbung';if (NUM_FARM==2){QQbB='onmouseover="self.status=\'\';return true;" ';}else{QQbB='onmouseover="self.status=\''+QQbB+'\';return true;" ';}if(IAS[9]==5)
QQbB='';var QQE=1;var QQa='http://www.falkag.de';// Ziel-Url
var QQF=(NUM_FARM==2)?'':'Falk AdSolution';var QQG=0;var QQH='';var QQI='';var QQJ='';var QQK='';var QQL='';var QQM=0;var QQN=0;var QQO=0;var QQP=0;var QQQ=1;var QQR=2;var QQe='';var QQS='';var QQi=[];var QQT=0;var QQU='';var QQV='';var QQW=false;var QQX=0;var QQY=false;var QQZ,QQAa,QQBa,QQCa,QQDa,QQEa,QQFa,QQGa,QQHa,QQIa;if(QQtA!=0)
{if((Ads_bid==0)||(Ads_bid==''))
QQs=QQbE(QQsA,QQtA);else
{QQk=BAS.length;QQs=0;while((BAS[QQs][0]!=Ads_bid)&&(QQs<QQk))
QQs++;if(QQs==QQk)
QQs=-1;}if(QQs!=-1)
QQd=BAS[QQs][0];}if(QQd>0)
{QQE=BAS[QQs][3];QQD=BAS[QQs][4];QQa=BAS[QQs][5];QQF=BAS[QQs][6];QQG=BAS[QQs][12];QQH=BAS[QQs][7];QQI=BAS[QQs][8];QQJ=BAS[QQs][9];QQK=BAS[QQs][10];QQL=BAS[QQs][11];QQf=BAS[QQs][13];QQg=BAS[QQs][14];QQM=BAS[QQs][15];QQN=BAS[QQs][16];QQQ=BAS[QQs][17];QQR=BAS[QQs][18];QQe=BAS[QQs][19];QQS=BAS[QQs][20];QQi=BAS[QQs][22];QQT=BAS[QQs][23];QQU=BAS[QQs][24];QQV=BAS[QQs][25];QQX=BAS[QQs][27];if (!QQeB)
QQeB=(BAS[QQs][26]==1);Ads_klist+=QQtA+'#';QQv=KAS[QQsA][4][25];if(QQv>0)
{if(typeof(Ads_fcount[QQv])=='undefined')
Ads_fcount[QQv]=1;else
Ads_fcount[QQv] ++;}}if(QQtA==-1)
{QQtA=99999999;QQd=99999999;QQC=true;}Ads_skid=QQtA;Ads_sbid=QQd;QQI=(QQI=='')?QQa:QQI;QQZ=(QQG&24);QQAa=QQB[QQG&3];QQDa=((QQG&64)>0)&&((Ads_opt&64)==0);QQBa=(QQG&128)>0;QQCa=(QQG&512)>0;QQW=(QQU=='_search')||(QQU=='_media');QQEa=((QQG&1024)>0)&&Ads_ModulEffects;QQFa=((QQG&8192)>0);QQZj=((Ads_opt&2)>0)&&!QQC&&(QQd!=0);QQGa=(QQG&2048)>0;QQHa=(QQS.length>0);QQY=(QQX==0)?false:true;QQf=(Ads_xl>0)?Ads_xl:QQf;QQg=(Ads_yl>0)?Ads_yl:QQg;QQM=(Ads_xp!='')?Ads_xp:QQM;QQN=(Ads_yp!='')?Ads_yp:QQN;QQO=(Ads_xp1!='')?Ads_xp1:QQO;QQP=(Ads_yp1!='')?Ads_yp1:QQP;QQyA=(QQG&4096)>0;Ads_opt|=(QQG&16384)>0?64:0;Ads_opt|=IAS[3]*32;if(QQwB.length!=0)
{QQqA+=QQwB[13];QQrA+=QQwB[14];}if (!QQZj||(QQZj&&(QQC==true||(Ads_cmd =='win'))))
{if(QQtA>0&&QQC==false&&QQsA!=-1)
QQy=QQiF(QQtA,QQsA,QQd,QQs,((QQG&4096)>0));QQz=QQhD(QQtA,QQd,QQy);QQpD(1,'Count-String [Click/Impression]',QQz[0]+'/'+QQz[1]);}if (QQY&&Ads_cmd!='win')
{var QQJa='nid='+Ads_nid+'&iid='+Ads_iid+'&bid='+QQd+'&rdm='+QQmD();document.write(QQkD(1,QQJa));}if(Ads_anc!='')
{QQw=true;QQA=Ads_anc;Ads_anc='';}QQa=QQnC(QQa);QQI=QQnC(QQI);if(Ads_cnturl!='')
{QQIa=QQoD(Ads_cnturl,'[url]',escape(QQa));QQa=QQoD(QQIa,'[url_plain]',QQa);QQIa=QQoD(Ads_cnturl,'[url]',escape(QQI));QQI=QQoD(QQIa,'[url_plain]',QQI);}if((QQE==3)||(QQE==4)||(QQE==8))
{Ads_LinkUrl=QQa;Ads_CountUrl=QQoC('',QQz[0]);Ads_CountUrl_ne=Ads_CountUrl.substr(0,Ads_CountUrl.length-1)+'ne=';Ads_ClickUrl=Ads_CountUrl+escape(QQa);Ads_MultiUrl=QQqC(QQi);Ads_ViewCode=QQkD(0,QQz[1]);Ads_ViewUrl=QQiD()+QQz[1];}if(QQE==1)
QQJ=QQiB[Ads_sec]+'/dat/bgf/'+QQD;if(QQwB.length!=0)
{if(!QQBa)
{QQBa=QQwB[0];QQDa=QQwB[1];QQCa=QQwB[2];QQR=QQwB[3];QQEa=QQwB[4];QQFa=QQwB[5];}if(!QQHa)
{QQHa=QQwB[6];QQS=QQwB[7];}QQM=QQwB[8];QQN=QQwB[9];QQO=QQwB[16];QQP=QQwB[17];QQZ=QQwB[10];IAS[2]=QQwB[11];IAS[11]=QQwB[12];QQA=QQwB[15];QQw=(QQA!='');QQwB=[];}if(QQE==5)
{QQwB=[QQBa,QQDa,QQCa,QQR,QQEa,QQFa,QQHa,QQS,QQM,QQN,QQZ,IAS[2],IAS[11],QQqA,QQrA,QQA,QQO,QQP];QQBa=false;QQHa=false;QQw=false;IAS[2]=0;}if((Ads_cmd=='lnk')&&(QQE!=5))
{self.location.href=QQoC(QQa,QQz[0]);QQBa=false;QQHa=false;QQw=false;QQE=6;return;}if(QQBa&&!QQW)
{if (!QQZj)
QQt=QQmI(QQf,QQg,QQM,QQN,QQZ,QQDa,QQCa,QQR,QQEa,QQFa,QQW,'');else
QQt=window;if(QQDa)
{if(window.innerHeight)
{QQf=QQt.innerWidth;QQg=QQt.innerHeight;}else
{QQf=QQt.document.body.clientWidth;QQg=QQt.document.body.clientHeight;}}if (!QQZj||(QQZj&&Ads_cmd=='win'))
if(QQCa&&(QQR==0))
QQt.blur();else if(QQCa)
QQt.setTimeout('window.blur();',QQR*1000);}else
QQt=window;if(QQw)
document.write(QQtD('Ads_place'+Ads_iid));else if(Ads_ModulEffects&&QQHa)
{if(QQZ==16)
QQZ=1;else if(QQZ==24)
QQZ=2;else
QQZ=0;QQtH(Ads_iid,QQf,QQg,QQM,QQN,QQZ,QQS,QQBa,QQt);QQuH(Ads_iid,Ads_sec);}QQpD(1,'Banner-Typ/PopUp',QQE+'/'+QQBa);var QQKa='';if (QQZj&&QQtA>0)
QQKa='QQy=QQiF('+QQtA+','+QQsA+','+QQd+','+QQs+','+((QQG&4096)>0)+');';QQoI(QQtA,QQd,QQf,QQg,QQM,QQN,QQZ,QQDa,QQCa,QQR,QQEa,QQFa,QQW,'',QQZj,QQKa);if (!QQC&&QQd==0&&QQtA)
{Ads_status[Ads_iid][0]=3;Ads_status[Ads_iid][3]=3;}else if (QQC)
{Ads_status[Ads_iid][0]=3;Ads_status[Ads_iid][3]=2;}else if (!QQC&&QQd>0)
{Ads_status[Ads_iid][1]=QQf;Ads_status[Ads_iid][2]=QQg;Ads_status[Ads_iid][3]=0;}if (!QQZj||(QQZj&&(Ads_cmd =='win')))
{if(QQE<2)
QQgI(QQt,QQBa,QQz,QQJ,QQa,QQAa,QQf,QQg,QQF,QQW,QQU,QQd,QQM,QQN);else if(QQE==2)
QQhI(QQt,QQBa,QQz,QQD,QQa,QQAa,QQf,QQg,QQF,QQH,QQI,QQGa,QQQ,QQV);else if(QQE==3)
QQiI(QQt,QQBa,QQz,QQtA,QQd,QQy,QQHa,QQf,QQg,QQT,QQU,QQw,'/dat/brf/',0,QQW,QQZj);else if(QQE==4)
QQjI(QQt,QQBa,QQz,QQK,QQL,QQHa,QQf,QQg,QQw);else if(QQE==5)
QQpC(QQtA,QQd,QQe,QQf,QQg);else if(QQE==8)
QQiI(QQt,QQBa,QQz,QQtA,QQd,QQy,QQHa,QQf,QQg,QQT,QQU,QQw,'/dat/bfx/',parseInt(QQe,10),QQW,QQZj);}QQpD(3,'Banner-display finished');QQtE();if(QQw)
{document.write(QQuD());setInterval('QQwD("Ads_place'+Ads_iid+'","'+QQA+'",'+QQf+','+QQg+');',20);}if(Ads_ModulEffects&&QQHa)
QQvH(Ads_iid);if(QQE!=5)
QQmC();Ads_idl+='#'+Ads_iid+'#';if((IAS[2]>0)&&(Ads_idl.indexOf('#'+IAS[2]+'#')==-1)&&(IAS[11]>(Math.random()*100)))
{Ads_kid=0;Ads_bid=0;Ads_xl=0;Ads_yl=0;QQbD(QQfB[Ads_sec]+'/dat/cjf/'+QQqD(IAS[2])+'.js');}QQk=Ads_cmb.length;for(QQl=0;QQl<QQk;QQl++)
{if(Ads_cmb[QQl]!='')
{QQx=Ads_cmb[QQl];Ads_cmb[QQl]='';QQl=QQk;Ads_pth='';Ads_iid='';eval(QQx);if(Ads_pth!='')
QQbD(QQfB[Ads_sec]+'/dat/njf/'+Ads_pth+'.js');else
QQbD(QQfB[Ads_sec]+'/dat/cjf/'+QQqD(Ads_iid)+'.js');}}}function CAS()
{QQsC(0);}function CASF()
{var QQLa=new Date();Ads_T=[0,0,'',0,0,'','','','',QQLa,0,0,0,0];QQsC(1);}function QQsC(QQMa)
{if(typeof(Ads_debug)=='undefined') Ads_debug=0;var QQNa=new Date(Ads_T[9]);var QQOa=new Date();Ads_T[9]=QQNa-QQOa;var QQPa=Ads_T[0]+'#'+Ads_T[1]+'#'+Ads_T[2]+'#'+Ads_T[3]+'#'+Ads_T[4]+'#'+Ads_T[5]+'#'+Ads_T[6]+'#'+escape(Ads_T[7])+'#'+escape(Ads_T[8])+'#'+Ads_T[9]+'#'+Ads_T[10]+'#'+Ads_T[11]+'#'+Ads_T[12]+'#'+Ads_T[13];document.cookie='ASLTRG'+NUM_FARM+'='+QQPa+QQfD(60*((QQMa==0)? 24:1));Ads_Data[NUM_FARM]=Ads_T;QQpD(1,'Load targeting-infos from server ('+((QQMa==0)? 'Origin':'Failover')+')',QQPa);if (QQsB==false)
{QQsB=true;SAS();}}function LAS(QQQa)
{Ads_iid=0;Ads_sec=(window.location.protocol.toLowerCase().indexOf('https')>-1)? 1:0;var QQb='pth='+QQQa+'&xl='+Ads_xl+'&yl='+Ads_yl;if(typeof(Ads_channels)!='undefined')
QQb+='&chn='+escape(Ads_channels);QQyA=false;document.write(QQkD(0,QQb));Ads_status[0]=[3,0,0,4];}function QQtC()
{QQwA=new Date();QQaB=-1;QQdB=0;document.cookie='BSUID=1'+QQfD(60*24*30);QQzA=false;if(typeof(Ads_debug)=='undefined') Ads_debug=0;if(typeof(Ads_klist)!='string') Ads_klist='';if(typeof(Ads_fcount)!='object') Ads_fcount=[];if(typeof(Ads_idl)!='string') Ads_idl='';if(typeof(garrIFrames)=='undefined') garrIFrames=[];QQpD(3,'Global Init');QQpD(1,'VAS Build Version:',Ads_Build);}function QQuC()
{if(typeof(Ads_sec)=='undefined') Ads_sec=IAS[1];QQpD(1,'Protocoll used',(Ads_sec==0)?'HTTP':'HTTPS');if(typeof(NUM_FARM)=='undefined')
NUM_FARM=1;if(typeof(Ads_farmid)!='undefined')
NUM_FARM=Ads_farmid;QQpD(1,'Setting configuration for farm',NUM_FARM);QQfB=[QQbA[NUM_FARM],QQcA[NUM_FARM]];QQgB=[QQhA[NUM_FARM],QQiA[NUM_FARM]];QQhB=[QQjA[NUM_FARM],QQkA[NUM_FARM]];QQiB=[QQdA[NUM_FARM],QQeA[NUM_FARM]];QQjB=[QQfA[NUM_FARM],QQgA[NUM_FARM]];}function QQvC()
{var QQPa=document.cookie+';';var QQRa=(QQPa.indexOf('BSUID=')!=-1);var QQSa=QQPa.indexOf('ASLTRG'+NUM_FARM+'=');var QQTa,QQAa;if (typeof(Ads_Data[NUM_FARM])!='undefined')
{QQpD(1,'Load targeting-infos targeting array ['+NUM_FARM+']',Ads_Data[NUM_FARM]);Ads_T=Ads_Data[NUM_FARM];return true;}if(QQSa!=-1)
{QQTa=QQPa.indexOf(';',QQSa);QQAa=QQPa.substring(QQSa+8,QQTa);Ads_T=QQAa.split('#');Ads_T[7]=unescape(Ads_T[7]);Ads_T[8]=unescape(Ads_T[8]);Ads_Data[NUM_FARM]=Ads_T;QQpD(1,'Load targeting-infos from cookie',QQAa);return true;}else
{QQpD(1,'#-#ASLDATA-load start','');QQbD(QQhB[Ads_sec]+ (QQRa?('?rdm='+QQmD()):''));QQpD(1,'#-#ASLDATA-load ende','');return false;}}function QQwC(QQUa,QQVa,QQWa)
{return true;}function QQxC()
{var QQXa=(QQyA?1:0);QQXa+=((QQeB)?2:0);QQpD(1,'FLG',QQXa);return QQXa;}function QQyC(QQYa,QQZa)
{if ((QQYa==QQxB)&&(QQZa==QQyB))
return true;else
return false;}function QQzC(QQAb,QQBb)
{var QQCb;var QQDb;QQDb=false;if(!isNaN(QQAb))
{QQCb=parseInt(QQAb);QQDb=QQCb>=0&&(QQBb||QQCb>0);}return QQDb;}function QQaD(QQEb)
{var QQFb,QQGb;var QQHb,QQIb,QQJb,QQKb,QQLb,QQMb;var QQZ,QQNb,QQOb,QQPb,QQQb;var QQRb;var QQSb;QQFb=QQEb.split('-');QQSb=false;QQGb=[];QQRb=true;if(QQFb[0]!=null&&QQFb[1]!=null)
{QQHb=QQFb[0];QQIb=QQFb[1];QQRb=QQRb&&QQzC(QQIb,false);if(QQRb&&QQFb[2]!=null)
{QQJb=QQFb[2];QQRb=QQzC(QQJb,false);if(QQRb&&QQFb[3]!=null)
{QQKb=QQFb[3];QQRb=QQzC(QQKb,true);if(QQRb&&QQFb[4]!=null)
{QQLb=QQFb[4];if(QQRb&&QQFb.length>5)
{QQZ=5;while(QQRb&&QQZ<QQFb.length)
{if(QQFb[QQZ]==''&&QQFb[QQZ+1]!=null)
{QQMb=QQFb[QQZ+1];QQRb=QQzC(QQMb,true);QQGb[QQGb.length]='-'+QQMb;QQZ=QQZ+2;}else
{QQMb=QQFb[QQZ];QQRb=QQzC(QQMb,true);QQGb[QQGb.length]=QQMb;QQZ=QQZ+1;}}QQRb=QQRb&&(QQGb.length==0||QQGb.length==2||QQGb.length==4);}}}}if(QQRb)
{QQSb=[QQHb,QQIb,QQJb,QQKb,QQLb];for (var intI=0;intI<QQGb.length;intI++)
{QQSb[QQSb.length]=QQGb[intI];}}}return QQSb;}QQtC();// Falk AdSolution - Copyright (c) 2004 by Falk eSolutions AG - All rights reserved (Build: 00000070)
function QQfI(QQHh,QQTj)
{return (QQHh==0)?'':' '+QQTj+'="'+QQHh+'"';}function QQgI(QQt,QQBa,QQz,QQJ,QQa,QQAa,QQf,QQg,QQF,QQW,QQU,QQd,QQM,QQN)
{QQJ=QQnC(QQJ);if(QQBa&&QQW&&!QQZj)
{QQp=QQfB[Ads_sec]+'/dat/dlv/aslframe.html?dat='+Ads_iid +'&kid='+QQtA+'&wrd='+escape(Ads_wrd) +'&bid='+QQd+'&prf='+escape(Ads_prf) +'&xl='+QQf+'&par='+escape(Ads_par) +'&yl='+QQg+'&cnturl='+Ads_cnturl+'&debug=0' +'&xp='+QQM+'&sec='+Ads_sec+'&bgc='+Ads_bgc +'&yp='+QQN+'&ref='+Ads_ref+'&opt=' +2 +'&cmd=win';QQpD(1,'Sidebar',QQp);QQtSide=window.open(QQp,QQU);}else
{if(QQBa)
QQkI(QQt,QQF);QQt.document.write('<a href="'+QQoC(QQa,QQz[0]) +'" target="'+QQAa+'" '+QQbB+'onmouseout="self.status=\'\';return true;">');QQt.document.write('<img src="'+QQJ+'"'+QQfI(QQf,'width')+QQfI(QQg,'height')+' border="0" id="Ads_img'+Ads_iid+'" name="Ads_img'+Ads_iid+'" alt="'+QQF+'"></a>');QQlD(QQt,QQz[1]);if(QQBa)
QQlI(QQt);}if (QQyC(Ads_iid,QQtA))
{QQtB='';QQvB=0;}}function QQhI(QQt,QQBa,QQz,QQD,QQa,QQAa,QQf,QQg,QQF,QQH,QQI,QQGa,QQQ,QQV)
{var QQWj=QQoD(QQz[0],'&rdm='+Ads_Timestamp,'');if(QQBa)
QQkI(QQt,QQF);QQa=QQoC(QQa,QQWj);QQI=QQoC(QQI,QQWj);QQD=QQiB[Ads_sec]+'/dat/bgf/'+QQD;QQH=QQiB[Ads_sec]+'/dat/bgf/'+QQH;QQjC=QQa;QQkC=QQoC('',QQWj);var QQXj=QQD;if(typeof(QQV)=='undefined') QQV='';if(QQV=='')
QQXj+='?clickTag='+escape(QQa)+'&url='+escape(QQa);else if(QQV!='0')
QQXj+='?'+QQV+'='+escape(QQa);var QQSc;if(QQQ<=QQsD(1))
{QQt.document.write('<OBJECT classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http'+((Ads_sec==1)?'s':'')+'://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=3,0,0,0" id=banner'+QQfI(QQf,'width')+QQfI(QQg,'height')+'">');QQt.document.write('<PARAM NAME=movie VALUE="'+QQXj+'"><PARAM NAME=play VALUE=true><PARAM NAME=autoplay VALUE=true><PARAM NAME=wmode VALUE=opaque><PARAM NAME=quality VALUE=autohigh><PARAM name=scale value=exactfit>');QQt.document.write('<EMBED src="'+QQXj+'" quality=autohigh autoplay=true play=true wmode=opaque scale=exactfit swLiveConnect=TRUE'+QQfI(QQf,'width')+QQfI(QQg,'height')+' TYPE="application/x-shockwave-flash" PLUGINSPAGE="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash"></EMBED></OBJECT>');}else
{QQt.document.write('<a href="'+QQI+'" target="'+QQAa+'" '+QQbB+' onmouseout="self.status=\'\';return true;"><img src="'+QQH+'"'+QQfI(QQf,'width')+QQfI(QQg,'height')+' border="0" alt="'+QQF+'"></a>');}QQlD(QQt,QQz[1]);if(QQBa)
QQlI(QQt);if (QQyC(Ads_iid,QQtA))
{QQtB='';QQvB=0;}}function QQiI(QQt,QQBa,QQz,QQc,QQd,QQy,QQHa,QQf,QQg,QQT,QQU,QQw,QQQa,QQYj,QQW,QQZj)
{var QQD=QQfB[Ads_sec]+QQQa+QQqD((QQYj>0)?QQYj:((QQT==0)?QQd:QQT));var QQAk,QQEg;var QQBk=[];QQBk=QQgD(QQc,QQd,QQy);iid=Ads_iid;bid=QQd;rdm=QQBk[2];if(QQBa||((QQHa||QQw)&&(QQqB||QQrB)))
{var QQCk='*';for(QQEg=1;QQEg<Ads_MultiUrl.length;QQEg++)
{QQa=Ads_MultiUrl[QQEg];QQCk+=QQa.substring(Ads_CountUrl.length,QQa.length)+'*';}QQAk=Ads_wid+'#'+Ads_iid+'#'+QQc+'#'+QQd+'#'+Ads_xwid+'#'+Ads_xiid+'#'+Ads_wrd+'#'+Ads_prf+'#'+Ads_par+'#'+Ads_Timestamp+'#'+rdm+'#'+(QQgB[Ads_sec]+QQpA[NUM_FARM]+'flg='+QQxC()+'&')+'#'+Ads_LinkUrl+'#'+QQCk+'#'+QQiD();}if(QQBa&&QQW&&!QQZj)
{window.open(QQD+'.html?'+escape(QQAk),QQU);}else if(QQBa)
{QQt.location.href=QQD+'.html?'+escape(QQAk);}else if((QQHa||QQw)&&(QQqB||QQrB))
{document.write('<iframe src="'+QQD+'.html?'+escape(QQAk)+'" width="'+QQf+'" height="'+QQg+'" noresize scrolling="no" hspace="0" vspace="0" frameborder="0" marginheight="0" marginwidth="0"></iframe>');}else
{rdm=QQBk[0];if(QQYj>0)
{Ads_xl=QQf;Ads_yl=QQg;QQlD(QQt,QQz[1]);if ((Ads_opt&4096)>0)
{QQpD(1,'Serve AFX Out Of Frame','');var QQCk='*';for(QQEg=1;QQEg<Ads_MultiUrl.length;QQEg++)
{QQa=Ads_MultiUrl[QQEg];QQpD(1,'Ads_MultiUrl['+QQEg+']',QQa.substring(Ads_CountUrl.length,QQa.length));QQaShort=QQa.substring(Ads_CountUrl.length,QQa.length);QQpD(1,'Index of',QQaShort.indexOf(".falkag.net/dat/bgf/trpix.gif&bidx="));if (QQaShort.indexOf(".falkag.net/dat/bgf/trpix.gif&bidx=")>=0)
{QQCk+='PX'+QQaShort.substring(QQaShort.indexOf('&')+5,QQaShort.length)+'*';}else
{QQCk+=QQaShort+'*';}}QQpD(1,'QQCk',QQCk);QQAk=Ads_wid+'#'+Ads_iid+'#'+QQc+'#'+QQd+'#'+Ads_xwid+'#'+Ads_xiid+'#'+Ads_wrd+'#'+Ads_prf+'#'+Ads_par+'#'+Ads_Timestamp+'#'+rdm+'#'+(QQgB[Ads_sec]+QQpA[NUM_FARM]+'flg='+QQxC()+'&')+'#'+Ads_LinkUrl+'#'+QQCk+'#'+QQiD()+'#'+NUM_FARM+'#'+QQfB[Ads_sec]+'#'+QQYj;var QQDk=document.referrer;var QQEk='';var QQFk='';var QQGk=QQDk.indexOf('://');if (QQGk>-1)
{QQEk=QQDk.substring(0,(QQGk+3));QQFk=QQDk.substring((QQGk+3),QQDk.length);var QQGk=QQFk.indexOf('/');if (QQGk>-1)
QQFk=QQFk.substring(0,QQGk);}QQpD(1,'Loading ',QQEk+QQFk+'/afx_frame.html?'+ escape(QQAk));document.write('<iframe src="'+QQEk+QQFk+'/afx_frame.html?'+escape(QQAk)+'" width="1" height="1" noresize scrolling="no" hspace="0" vspace="0" frameborder="0" marginheight="0" marginwidth="0"></iframe>');}else
{if ((typeof(Ads_FXPL)=='undefined')||(Ads_FXPL==false))
{QQbD(QQfB[Ads_sec]+'/dat/dlv/afxplay.js');Ads_FXPL=true;}QQbD(QQD+'.js');}}else
QQbD(QQD+'.js');}if (QQyC(Ads_iid,QQtA))
{QQtB='';QQvB=0;}}function QQjI(QQt,QQBa,QQz,QQK,QQL,QQHa,QQf,QQg,QQw)
{QQL=QQnC(unescape(QQL));QQK=QQnC(unescape(QQK));if(QQBa)
QQt.location.href=QQK;else
{if(((QQHa||QQw)&&QQqB)||(QQL==''))
document.write('<iframe src="'+QQK+'" width="'+QQf+'" height="'+QQg+'" noresize scrolling="no" hspace="0" vspace="0" frameborder="0" marginheight="0" marginwidth="0"></iframe>');else
QQbD(QQL);}QQlD(window,QQz[1]);if (QQyC(Ads_iid,QQtA))
{QQtB='';QQvB=0;}}function QQkI(QQt,QQF)
{QQt.document.open();QQt.document.write('<html><head><title>'+QQF+'</title></head><body topmargin="0" leftmargin="0" rightmargin="0" marginwidth="0" marginheight="0"><table width="100%" height="100%" border="0" cellspacing="0" cellpadding="0" align="center"><tr><td valign="middle"><center>');}function QQlI(QQt)
{QQt.document.write('</center></td></tr></table></body></html>');QQt.document.close();}function QQmI(QQf,QQg,QQM,QQN,QQZ,QQDa,QQCa,QQR,QQEa,QQFa,QQW,QQU)
{var QQu='locationbar=no,directories=no,statusbar=no,toolbar=no,location=no,menubar=no,personalbar=no';var QQHk='Ads_Popup'+Ads_iid;var QQIk,QQJk;var QQKk=0;var QQLk=0;if (!QQW&&QQU!='')
QQHk=QQU;QQu=QQnI(QQf,QQg,QQM,QQN,QQZ,QQDa,QQCa,QQR,QQEa,QQFa,QQW,QQU,QQZj);if((Ads_opt&32)>0)
QQHk+=''+Math.round(Math.random()*100000);QQt=open('',QQHk,QQu);if(QQDa&&(!QQnB))
QQt.moveTo(0,0);if(QQEa)
QQcI(QQt,QQf,QQg);return QQt;}function QQnI(QQf,QQg,QQM,QQN,QQZ,QQDa,QQCa,QQR,QQEa,QQFa,QQW,QQU,QQZj)
{var QQu='locationbar=no,directories=no,statusbar=no,toolbar=no,location=no,menubar=no,personalbar=no';var QQHk='Ads_Popup'+Ads_iid;var QQIk,QQJk;var QQKk=0;var QQLk=0;if (!QQW&&QQU!='')
QQHk=QQU;if(QQDa)
{if (QQoB)
{QQKk=10;QQLk=30;}else if (QQpB)
{QQKk=20;QQLk=35;}QQu+=',scrollbars=no,resizable=no,width='+(screen.availWidth-QQKk)+',height='+(screen.availHeight-QQLk)+',screenX=0,screenY=0';if(QQnB)
QQu='fullscreen=yes';}else
{if(QQEa)
QQu+=',resizable=yes,width=90,height=70,innerWidth=90,innerHeight=70';else
QQu+=',resizable=no,width='+QQf+',height='+QQg;if(QQFa)
QQu+=',scrollbars=yes';else
QQu+=',scrollbars=no';if((Ads_opt&64)>0)
QQu='locationbar=yes,scrollbars=yes,directories=yes,statusbar=yes,toolbar=yes,location=yes,menubar=yes,personalbar=yes,resizable=yes,width='+QQf+',height='+QQg;if(QQZ==16)
{QQM=(screen.width-QQf-25)*QQM/100;QQN=(screen.height-QQg-50)*QQN/100;}else if(QQZ==24)
{QQM=(screen.width-QQf-25)*Math.random();QQN=(screen.height-QQg-50)*Math.random();}if (!QQqB)
QQu+=",screenX="+QQM+",screenY="+QQN;else
QQu+=",left="+QQM+",top="+QQN;}return QQu;}function QQoI(QQtA,QQd,QQf,QQg,QQM,QQN,QQZ,QQDa,QQCa,QQR,QQEa,QQFa,QQW,QQU,QQZj,QQKa)
{var QQMk='';QQMk='<scr'+'ipt language="JavaScript">'+'function Ads_PopUp() {';if (Ads_cmd!='win'&&QQZj&&(QQd>0))
{QQpD(1,'POP ON EXIT','');var QQHk='Ads_Popup'+Ads_iid;if (!QQW&&QQU!='')
QQHk=QQU;if((Ads_opt&32)>0)
QQHk+=''+Math.round(Math.random()*100000);QQu=QQnI(QQf,QQg,QQM,QQN,QQZ,QQDa,QQCa,QQR,QQEa,QQFa,QQW,'',true);QQp=QQfB[Ads_sec]+'/dat/dlv/aslframe.html?dat='+Ads_iid +'&kid='+QQtA+'&wrd='+escape(Ads_wrd) +'&bid='+QQd+'&prf='+escape(Ads_prf) +'&xl='+QQf+'&par='+escape(Ads_par) +'&yl='+QQg+'&cnturl='+Ads_cnturl+'&debug=0' +'&xp='+QQM+'&sec='+Ads_sec+'&bgc='+Ads_bgc +'&yp='+QQN+'&ref='+Ads_ref+'&opt=' +2 +'&cmd=win';QQkB[QQkB.length]='QQt=open(\''+QQp+'\',\''+QQHk+'\',\''+QQu+'\');';}for (var intI=0 ;intI<QQkB.length ;intI++)
{QQMk+=QQkB[intI];}QQMk+=QQKa;QQMk+='}'+'</scr'+'ipt>';document.writeln(QQMk);}// Falk AdSolution - Copyright (c) 2004 by Falk eSolutions AG - All rights reserved (Build: 00000070)
var QQwE=[];var QQxE=[];var QQyE;function QQzE(QQUg,QQVg,QQWg,QQTe)
{if(typeof(QQUg)=='undefined')
return [];var QQl,QQk;var QQXg=[];var QQYg=QQUg.split('x');var QQZg=QQYg[0];var QQAh=QQVg-QQZg;var QQk=QQYg.length;QQxE[QQTe]=[];for(QQl=1;QQl<QQk;QQl++)
{QQFi=QQYg[QQl].split(':');if(QQWg&&(QQFi[2]==-1))
QQXg[QQFi[0]]=[QQFi[1],-1];QQFi[2]-=QQAh;if(QQFi[2]>0)
QQXg[QQFi[0]]=[QQFi[1],QQFi[2]];if (typeof(QQxE[QQTe])=='undefined')
QQxE[QQTe]=[];QQxE[QQTe][QQxE[QQTe].length]=QQFi[0];}return QQXg;}function QQaF(QQXg,QQVg,QQTe)
{var QQUc;var QQUg=QQVg;var QQl;if (typeof(QQxE[QQTe])!='undefined')
{for (var intI=0;intI<QQxE[QQTe].length;intI++)
{QQl=QQxE[QQTe][intI];if (typeof(QQXg[QQl])!='undefined')
{QQUg+='x'+QQl+':'+QQXg[QQl][0]+':'+QQXg[QQl][1];}}}return QQUg;}function QQbF(QQBh,QQCh)
{while(QQBh.length>800)
QQBh=QQBh.substr(0,QQBh.lastIndexOf('#',QQBh.length-2)+1);QQwE[QQCh]=QQBh;}function QQcF(QQCh,QQCb)
{var QQDh='111';var QQEh='@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`';var QQk=0;var QQAb='#'+QQCb+':';var QQBh=QQwE[QQCh];var QQFh='';var QQZ=QQBh.indexOf(QQAb);var QQGh=new Date();var QQHh,QQIh,QQJh,QQKh,QQJe;var QQLh,QQMh,QQNh,QQOh;if(QQBh=='')
QQBh='#';if(QQZ>-1)
{QQIh=QQBh.substr(QQZ+QQAb.length,3+QQCh);if(QQZ>0)
QQFh=QQBh.substr(0,QQZ);QQHh=QQBh.length-QQZ-QQAb.length-3-QQCh;if(QQHh>0)
QQFh+=QQBh.substr(QQZ+QQAb.length+3+QQCh,QQHh);QQBh=QQFh;QQJh=new Date(QQEh.indexOf(QQIh.charAt(0))+2000,QQEh.indexOf(QQIh.charAt(1))-1,QQEh.indexOf(QQIh.charAt(2)));QQGh.setHours(0);QQGh.setMinutes(0);QQGh.setSeconds(0);QQKh=(QQGh.getTime()-QQJh.getTime())/1000/60/60/24;intAltWTag=(QQJh.getDay()==0?7:QQJh.getDay());intNeuWTag=(QQGh.getDay()==0?7:QQGh.getDay());intAltMTag=QQJh.getDate();intNeuMTag=QQGh.getDate();QQDh=((QQKh>0.1)?'1':'0')+(((QQKh>6)||(intAltWTag>intNeuWTag))?'1':'0')+((((QQKh>29)||(intAltMTag>intNeuMTag))&&(QQCh!=1&&QQCh!=14))?'1':'0');if(QQCh==1||QQCh==14)
QQk=QQEh.indexOf(QQIh.charAt(3));}QQIh='#'+QQCb+':';QQJe=QQGh.getYear();if(QQJe<1900)
QQJe+=1900;QQIh+=QQEh.charAt(QQJe-2000);QQIh+=QQEh.charAt(QQGh.getMonth()+1);QQIh+=QQEh.charAt(QQGh.getDate());if(QQCh==1||QQCh==14)
{QQk++;if(QQk>21)
QQk=21;QQIh+=QQEh.charAt(QQk);QQDh+=QQEh.charAt(QQk);}QQBh=QQIh+QQBh;QQbF(QQBh,QQCh);return QQDh;}function QQdF(QQAb,QQCh,QQPh)
{var QQSa,QQTa,QQHh,QQQh,QQRh;var QQBh=QQwE[QQCh];var QQFh='';var QQSh='';var QQTh=-1;if(QQBh=='')
QQBh='#';QQAb='#'+QQAb+'-';QQSa=QQBh.indexOf(QQAb);if(QQSa!=-1)
QQTa=QQBh.indexOf('#',QQSa+1);if((QQSa!=-1)&&(QQTa!=1))
{QQQh=QQBh.substring(QQSa+QQAb.length,QQTa);if(QQSa>0)
QQFh=QQBh.substr(0,QQSa);QQHh=QQBh.length-QQTa;if(QQHh>0)
QQFh+=QQBh.substr(QQTa,QQHh);QQBh=QQFh;if(QQCh==6)
{QQRh=QQQh.split('-');QQSh=QQRh[0];QQQh=QQRh[1];}QQTh=QQPh-parseInt(QQQh,10);if(QQTh>1200)
QQTh=-1;}QQwE[QQCh]=QQBh;return [QQTh,QQSh];}function QQeF(QQc)
{var QQUh=new Date();var QQTh=QQUh.getHours()*60*60+QQUh.getMinutes()*60+QQUh.getSeconds();var QQVh,QQWh;QQVh=QQdF(Ads_wid,6,QQTh);QQWh=QQdF(QQc,5,QQTh);var QQXh=(QQVh[0]==-1);var QQYh=(QQWh[0]==-1);var QQZh=(QQXh?'1':'0')+(QQYh?'1':'0');if(!QQXh)
QQZh+=QQnD(QQVh[0],4)+QQVh[1];QQbF('#'+Ads_wid+'-'+Ads_iid+'-'+QQTh+QQwE[6],6);QQbF('#'+QQc+'-'+QQTh+QQwE[5],5);return QQZh;}function QQfF()
{var QQWb=QQdD();var QQl,QQAi,QQUc,QQBi,QQCi,QQDi,QQEi,QQFi,QQCh;var QQGi,QQHi;var QQPa=document.cookie;var QQWg=(QQPa.toLowerCase().indexOf('sestest')>-1);document.cookie='SESTEST=1'+QQfD(-1);var QQIi=QQPa.split(';');var QQk=QQIi.length;var QQPc=new Date();QQyE=Math.round(QQPc.getTime()/1000/60);QQwE=['','',[],'','','','',[],[],[],QQdB,'',[],'',''];QQwE=QQgF('',QQIi,QQk,QQWg);if(Ads_uid!='')
{QQIi=Ads_userdata.split(';');QQk=QQIi.length;QQwE[2]=[];for(QQl=1;QQl<(QQk-1);QQl++)
{QQDi=QQIi[QQl].split(',');QQwE[2][QQDi[0]]=[QQDi[1],1];}}if(QQwE[3]=='1')
QQzA=true;}function QQgF(QQWb,QQIi,QQk,QQWg)
{var QQl;var QQwE;var QQUc;QQwE=['','',[],'','','','',[],[],[],QQdB,'',[],'',''];for(QQl=0;QQl<QQk;QQl++)
{QQCh=-1;QQDi=QQIi[QQl].split('=');QQUc=QQDi[0];QQCi=QQDi[1];if(QQUc.charAt(0)==' ')
QQUc=QQUc.substr(1,QQUc.length-1);if(QQUc.substr(0,QQWb.length)==QQWb)
QQBi=QQUc.substring(QQWb.length,QQUc.length);else
QQBi='';if(QQBi=='KIDYMD')
QQwE[1]=QQCi;else if(QQBi=='WIDYMD')
QQwE[0]=QQCi;else if(QQUc=='BSUID')
QQwE[3]=QQCi;else if(QQUc=='BNDLVL')
QQwE[10]=QQCi;else if(QQBi=='VISKAM')
QQwE[5]=QQCi;else if(QQBi=='VISWEB')
QQwE[6]=QQCi;else if(QQBi=='FRQSTR')
{if (QQCi.indexOf("|")!=-1)
QQDi=QQCi.split('|');else
QQDi=QQCi.split(',');QQwE[2]=QQzE(QQDi[0],QQyE,QQWg,2);QQwE[7]=QQzE(QQDi[1],QQyE,QQWg,7);QQwE[8]=QQzE(QQDi[2],QQyE,QQWg,8);QQwE[9]=QQzE(QQDi[3],QQyE,QQWg,9);QQwE[12]=QQzE(QQDi[4],QQyE,QQWg,12);}if(QQBi=='KIDCYMD')
QQwE[14]=QQCi;else if(QQBi=='WIDCYMD')
QQwE[13]=QQCi;}return QQwE;}function QQhF(QQc,QQPd)
{var QQJi,QQKi,QQEe,QQLi;var QQMi='';var QQWb=QQdD();var QQNi=KAS[QQPd][4][5];if(KAS[QQPd][4][4]>0)
QQMi=QQeD(QQNi);else if((KAS[QQPd][5]&1)>0)
{QQMi=QQeD(20);QQNi=20;}if(QQMi!='')
{QQEe=parseInt(QQjF(QQc,2)+1,10);if(Ads_uid!='')
{QQJi=Ads_userdata.split(';'+QQc+',');if(QQJi.length==2)
{QQKi=Ads_userdata.split(','+QQc+';');Ads_userdata=QQJi[0]+';'+QQKi[1];}Ads_userdata+=QQc+','+QQEe+','+QQNi+','+QQc+';';document.write('<img src="http://uboot.as-eu.falkag.net/usr?cmd=write&id='+Ads_uid+'&data='+Ads_userdata+'&rdm='+Math.random()+'" width="1" height="1">');}else
QQkF(QQc,2,QQEe,QQNi);}}function QQiF(QQc,QQPd,QQd,QQs,QQOi)
{var QQWb=QQdD();var QQy=[];var QQPi,QQPa,QQQi;QQhF(QQc,QQPd);if(QQd>0)
{if(BAS[QQs][2][4]>0)
QQkF(QQd,9,QQjF(QQd,9)+1,BAS[QQs][2][5]);}if(((KAS[QQPd][4][22]&1)>0)&&(IAS[4]>0))
QQkF(Ads_wid,7,QQjF(Ads_wid,7)+1,IAS[5]);if(((KAS[QQPd][4][22]&2)>0)&&(IAS[6]>0))
QQkF(Ads_nid,8,QQjF(Ads_nid,8)+1,IAS[7]);if ((typeof(IAS[17])!='undefined')&&(typeof(QQbC[Ads_wid])!='undefined')&&(typeof(KAS[QQPd][13])!='undefined'))
{if(((KAS[QQPd][4][22]&4)>0)&&(KAS[QQPd][13]>0)&&(QQbC[Ads_wid].length>0)&&(typeof(QQbC[Ads_wid][KAS[QQPd][13]])!='undefined'))
{arrFamily=QQbC[Ads_wid][KAS[QQPd][13]];QQkF(arrFamily[0],12,QQjF(arrFamily[0],12)+1,arrFamily[2]);}}QQPa=QQaF(QQwE[2],QQyE,2)+'|' +QQaF(QQwE[7],QQyE,7)+'|' +QQaF(QQwE[8],QQyE,8)+'|' +QQaF(QQwE[9],QQyE,9)+'|' +QQaF(QQwE[12],QQyE,12);QQPi=QQcF(1,QQc);QQQi=QQPi.substr(0,3)+QQcF(0,Ads_wid)+QQPi.substr(3,1);QQy[1]='&bls3='+QQQi;QQuB=QQQi;QQy[1]+='&bls4='+QQeF(QQc);strClickAuswertung=QQcF(14,QQc);QQy[0]='&ucl='+strClickAuswertung.substr(0,3)+QQcF(13,Ads_wid)+strClickAuswertung.substr(3,1);if(QQzA)
QQy[1]+='&uid=1';QQpD(1,'SETTING TOP-LEVEL DOMAIN',QQPa);document.cookie='FRQSTR='+QQPa+QQfD(60*24*365);document.cookie='WIDYMD='+QQwE[0]+QQfD(60*24*30);document.cookie='KIDYMD='+QQwE[1]+QQfD(60*24*30);document.cookie='VISKAM='+QQwE[5]+QQfD(20);document.cookie='VISWEB='+QQwE[6]+QQfD(20);QQpD(1,'Cookie Auswertung [Click/Impression]',QQy[0]+'/'+QQy[1]);return QQy;}function QQjF(QQCb,QQTe)
{if(typeof(QQwE[QQTe][''+QQCb+''])!='undefined')
return parseInt(QQwE[QQTe][''+QQCb+''],10);else
return 0;}function QQkF(QQCb,QQTe,QQEe,QQNi)
{if(typeof(QQwE[QQTe][''+QQCb+''])!='undefined')
QQwE[QQTe][''+QQCb+''][0]=QQEe;else
{if (typeof(QQxE[QQTe])=='undefined')
QQxE[QQTe]=[];QQxE[QQTe][QQxE[QQTe].length]=QQCb;QQwE[QQTe][''+QQCb+'']=[QQEe,QQNi];}}// Falk AdSolution - Copyright (c) 2004 by Falk eSolutions AG - All rights reserved (Build: 00000070)
function QQxD(QQBd,QQCd)
{var QQl=0;var QQk=QQBd.length;if(QQk==0)
return -1;while((QQl<QQk-1)&&(QQCd>QQBd[QQl][1]))
{QQCd-=QQBd[QQl][1];QQl++;}return QQBd[QQl][0];}function QQyD(QQDd,QQEd,QQFd)
{var QQl,QQGd,QQHd,QQId;if(QQDd>QQFd)
{QQGd=QQFd/QQDd;for(QQl=QQEd;QQl<QQlB.length;QQl++)
QQlB[QQl][1]*=QQGd;QQDd=QQFd;}QQFd-=QQDd;return QQFd;}function QQzD()
{var QQDb,QQJd,QQKd,QQLd,QQMd;var QQNd=-2;var QQOd=KAS.length;var QQFd=100;var QQPd,QQc,QQId,QQQd,QQRd,QQSd,QQTd,QQUd,QQVd;var QQDd=0;var QQEd;QQlB=[];for (QQPd=0;QQPd<QQOd;QQPd++)
{QQMd=((KAS[QQPd][5]&2)>0);if(KAS[QQPd][2]!=QQNd)
{if(QQNd!=-2)
QQFd=QQyD(QQDd,QQEd,QQFd);QQNd=KAS[QQPd][2];QQDd=0;QQEd=QQlB.length;}QQQd=KAS[QQPd][8];QQRd=KAS[QQPd][10];QQSd=IAS[10];if((QQSd-QQRd)>0)
QQQd=QQQd*QQSd/(QQSd-QQRd);QQId=KAS[QQPd][1];if(QQQd<=0)
QQQd=QQId;QQTd=(QQId/QQQd-1)*2+1;var QQWd=QQTd;var QQXd=false;if (QQTd>10||QQTd<0.1)
QQXd=true;if(QQTd>10)
QQTd=10;else if (QQTd<0.1)
QQTd=0.1;if (QQXd)
QQpD(1,'Factor (before:after)',QQWd+':'+QQTd);QQUd=KAS[QQPd][3];QQId=QQId*QQTd*100/((QQUd==0)?100:QQUd);if(isNaN(QQId))
QQId=0;QQLd=KAS[QQPd][4];QQDb=QQrE(QQLd,0,KAS[QQPd][0],((KAS[QQPd][5]&4)>0),QQPd);QQKd=false;if(QQLd.length>0)
{QQKd=((QQLd[0]==0)&&!((QQLd[2]==0)&&(QQLd[3]==1439)));QQJd=(!QQKd||QQpE(QQLd[2],QQLd[3]));if(QQKd)
QQId=QQId*100/KAS[QQPd][9];if(QQDb&&!QQJd&&!QQMd)
{QQqA+='9'+KAS[QQPd][0]+'-';}QQDb=(QQDb&&QQJd);}if((KAS[QQPd][5]&8)>0)
QQId=KAS[QQPd][1];if(QQMd&&QQDb)
{QQc=KAS[QQPd][0];QQrA+=QQc+'-';QQhF(QQc,QQPd);}else if(QQDb)
{QQlB[QQlB.length]=[QQPd,QQId,QQKd,QQId];QQDd+=QQId;}else
{}}QQFd=QQyD(QQDd,QQEd,QQFd);}function QQaE()
{QQzD();var QQYd,QQPd,QQl,QQId;var QQOd=QQlB.length;var QQZd=0;for (QQPd=0;QQPd<QQOd;QQPd++)
{QQl=QQlB[QQPd][0];QQId=QQlB[QQPd][1];QQYd=Math.round(QQId/QQlB[QQPd][3]*10)-1;if(QQYd>9)
QQYd=9;if((QQYd>=0)&&(KAS[QQl][0]>0))
QQqA+=QQYd+''+KAS[QQl][0]+'-';QQZd+=QQId;}return QQxD(QQlB,QQZd*Math.random());}function QQbE(QQPd,QQc)
{var QQAe=[];var QQBe=BAS.length;var QQCe=((KAS[QQPd][5]&1)>0);var QQZd=0;var QQs,QQId,QQDe,QQEe,QQFe,QQGe;var QQHe=true;for (QQs=0;QQs<QQBe;QQs++)
{strInhalt=BAS[QQs][21];QQGe=((strInhalt.length<3)||(strInhalt.indexOf('#'+Ads_iid+'#')>-1));if(((Ads_xl>1)||(Ads_yl>1))&&((BAS[QQs][13]>1)||(BAS[QQs][14]>1)))
{QQHe=((Ads_xl==BAS[QQs][13])&&(Ads_yl==BAS[QQs][14]));}if(QQHe&&QQGe&&QQrE(BAS[QQs][2],1,BAS[QQs][0],true,QQs))
{QQId=BAS[QQs][1];QQAe[QQAe.length]=[QQs,QQId];QQZd+=QQId;}else
{}}QQBe=QQAe.length;if(QQCe)
{QQEe=QQjF(QQc,2);if(QQBe>0)
QQs=QQAe[QQEe%QQBe][0];else
QQs=-1;}else
QQs=QQxD(QQAe,QQZd*Math.random());return QQs;}// Falk AdSolution - Copyright (c) 2004 by Falk eSolutions AG - All rights reserved (Build: 00000070)
var QQcE=false;var QQdE;var QQeE;var QQfE =(typeof(QQfE)=='undefined')? 0:QQfE;function QQgE(QQIe)
{return QQnD(QQIe.getHours(),2)+':'+QQnD(QQIe.getMinutes(),2)+':'+QQnD(QQIe.getSeconds(),2);}function QQhE(QQIe)
{var QQJe=QQIe.getYear();if(QQJe<1900)
QQJe+=1900;return QQnD(QQJe,4)+'-'+QQnD(QQIe.getMonth()+1,2)+'-'+QQnD(QQIe.getDate(),2);}function QQiE()
{if(QQcE)
return;var QQKe,QQLe,QQMe,QQl,QQNe;var QQOe=new Date();var QQPe=new Date();QQPe.setTime(QQOe-0+parseInt(Ads_T[9],10));QQKe=QQwE[1].split('#');QQLe=QQKe.length-1;QQMe=',';for(QQl=1;QQl<QQLe;QQl++)
{QQNe=QQKe[QQl].split(':');QQMe+=QQNe[0]+',';}QQcE=true;QQdE=';keyword='+escape(Ads_wrd) +';user-domain='+Ads_T[5] +';user-ip='+Ads_T[6] +';url='+escape(window.location.href) +';referrer='+escape(document.referrer) +';accept-language='+escape(Ads_T[7]) +';accept-charset='+escape(Ads_T[8]) +';user-agent='+escape(navigator.userAgent) +';browser-name='+escape(navigator.appName) +';browser-version='+escape(navigator.appVersion) +';flash-version='+QQsD(0) +';user-day='+(QQOe.getDay()==0?7:QQOe.getDay()) +';user-time='+QQgE(QQOe) +';user-date='+QQhE(QQOe) +';server-day='+(QQPe.getDay()==0?7:QQPe.getDay()) +';server-time='+QQgE(QQPe) +';server-date='+QQhE(QQPe) +';campaigns='+QQMe +';';if(navigator.appVersion.substring(0,1)>'3')
{var QQQe=0;var QQRe=0;if (typeof(window.innerWidth)=='undefined'&&document.body!=null)
{QQQe=document.body.clientWidth;QQRe=document.body.clientHeight;}else
{QQQe=window.innerWidth;QQRe=window.innerHeight;}QQdE+='java='+(navigator.javaEnabled()?'1':'0') +';screen-width='+screen.width +';screen-height='+screen.height +';window-width='+QQQe +';window-height='+QQRe +';color-depth='+screen.colorDepth +';';}QQpD(1,'Environment values',QQdE);}function QQjE(QQSe,QQk,QQCb,QQTe,QQUe,QQVe,QQWe)
{var QQXe;if((QQk>0)&&(QQSe>0))
{QQXe=((QQjF(QQCb,QQTe)<QQk)&&(QQzA||QQWe));if((QQXe?1:0)==QQUe)
return QQUe;QQeE[QQVe]=QQXe;}return 2;}function QQkE(QQYe,QQZe,QQAf,QQUe,QQVe)
{var QQXe;if(QQYe.length>1)
{QQXe=(QQYe.indexOf('#'+QQZe+'#')!=-1);QQXe=QQAf>0?!QQXe:QQXe;QQeE[QQVe]=QQXe;if((QQXe?1:0)==QQUe)
return QQUe;}return 2;}function QQlE(QQSe,QQBf,QQCb,QQTe,QQUe,QQVe,QQWe)
{var QQXe=true;if (typeof(QQBf)=='undefined')
QQBf=[];if (typeof(QQbC[Ads_wid])=='undefined')
QQbC[Ads_wid]=[];if(QQSe>0&&QQCb>0)
{if ((QQBf.length>0)&&(QQbC[Ads_wid].length==0))
{for (intI=0 ;intI<QQBf.length ;intI++)
{QQbC[Ads_wid][QQBf[intI][0]]=[QQBf[intI][1],QQBf[intI][2],QQBf[intI][3]];if (QQBf[intI][0]==QQCb)
{QQvIndex=intI;}}if (typeof(QQvIndex)=='undefined')
return 2;intReturn=QQjE(QQSe,QQBf[QQvIndex][2],QQBf[QQvIndex][1],QQTe,QQUe,QQVe,QQWe);return intReturn;}else if (QQbC[Ads_wid].length>0)
{if (typeof(QQbC[Ads_wid][QQCb])=='undefined')
return 2;intReturn=QQjE(QQSe,QQbC[Ads_wid][QQCb][1],QQbC[Ads_wid][QQCb][0],QQTe,QQUe,QQVe,QQWe);return intReturn;}}return 2;}function QQmE(QQYe,QQAf,QQUe,QQCf,QQVe)
{if(QQYe=='')
return 2;var QQl,QQFc,QQDf,QQEf,QQEc,QQFf,QQGf,QQHf,QQIf;var QQDc='!"%&\'()*+,-./:;<=>?@[\\]^{|}~§ ';var QQXe=false;QQYe=QQYe.substr(1,QQYe.length-2);var QQLd=QQYe.split('#');var QQk=QQLd.length;if(QQk>0)
{if(QQCf)
{QQFc='';QQFf=Ads_wrd.length;for(QQl=0;QQl<QQFf;QQl++)
{QQEc=Ads_wrd.charAt(QQl);if(QQDc.indexOf(QQEc)!=-1)
QQEc='#';QQFc+=QQEc;}QQFc='#'+QQFc.toLowerCase()+'#';QQDf=QQFc;}else
{QQFc='#'+Ads_T[5]+'#';arrIP=Ads_T[6].split('.');QQDf='';for (var intI=0;intI<arrIP.length;intI++)
{if (intI!=0)
QQDf+='.';QQDf+=QQnD(parseInt(arrIP[intI]),3);}QQDf='#'+QQDf+'#';}for(QQl=0;(QQl<QQk)&&(QQXe==false);QQl++)
{QQHf=QQLd[QQl].toLowerCase();QQGf=false;if(QQHf.substring(0,1)=='$')
{QQHf=QQHf.substring(1,QQHf.length);QQGf=true;}QQEf=false;QQIf=QQFc;if(QQHf.substring(0,1)=='!')
{QQHf=QQHf.substring(1,QQHf.length);QQIf=QQDf;QQEf=true;}if(QQCf)
QQHf='#'+QQHf;if(!QQEf)
QQHf+='#';QQXe=(QQIf.indexOf(QQHf)!=-1);if (QQEf)
QQpD(1,'IP Targeting',QQXe);if(QQGf)
{QQXe=!QQXe;QQl=QQk;}}QQXe=QQAf>0?!QQXe:QQXe;if((QQXe?1:0)==QQUe)
return QQUe;QQeE[QQVe]=QQXe;}return 2;}function QQnE(QQJf,QQKf)
{var QQLf=[];var QQMf=0;var QQl,QQNf;var QQk=QQJf.length;for(QQl=0;QQl<QQk;QQl++)
{QQNf=QQJf[QQl];if(QQNf>=0)
{QQLf[QQMf]=QQKf[QQNf];QQMf++;}else if(QQNf==-2)
{QQMf--;QQLf[QQMf-1]=(QQLf[QQMf-1]&&QQLf[QQMf]);}else if(QQNf==-4)
{QQMf--;QQLf[QQMf-1]=(QQLf[QQMf-1]||QQLf[QQMf]);}else if(QQNf==-3)
{QQLf[QQMf-1]=(!QQLf[QQMf-1]);}}return QQLf[QQMf-1];}function QQoE(QQLd,QQOf,QQAf,QQPf,QQQf,QQUe,QQVe)
{var QQXe,QQUc,QQRf,QQSf,QQTf,QQUf,QQE,QQVf;var QQWf,QQXf;var QQl=0;var QQk=QQLd.length;var QQKf=[];var QQYf=QQOf.toLowerCase();for(QQl=0;QQl<QQk;QQl++)
{QQUc=QQLd[QQl][0];QQRf=QQLd[QQl][1];QQE=QQLd[QQl][2];QQVf=QQLd[QQl][3];QQWf=QQYf.indexOf(';'+QQUc+'=');if(QQWf>-1)
{QQXf=QQOf.indexOf(';',QQWf+1);if(QQXf>QQWf)
QQUf=unescape(QQOf.substring(QQWf+2+QQUc.length,QQXf));else
QQUf='';if(QQE==5)
QQE=1;if(QQE==1)
QQSf=0;else
QQSf='';if((QQVf==9)||(QQVf==10))
{QQTf=QQRf.split(';');if(QQTf.length==2)
{QQRf=QQTf[0];QQSf=QQTf[1];}else
QQVf=0;}if(QQE==1)
{QQUf=parseFloat(QQUf);QQRf=parseFloat(QQRf);QQSf=parseFloat(QQSf);}if((QQVf>5)&&(QQVf<9))
{if (typeof(QQUf)!='string')
QQUf=QQUf+'';if (typeof(QQRf)!='string')
QQRf=QQRf+'';QQUf=QQUf.toLowerCase();QQRf=QQRf.toLowerCase();}if(QQVf==0)
QQXe=(QQUf==QQRf);else if(QQVf==1)
QQXe=(QQUf!=QQRf);else if(QQVf==2)
QQXe=(QQUf<QQRf);else if(QQVf==3)
QQXe=(QQUf<=QQRf);else if(QQVf==4)
QQXe=(QQUf>QQRf);else if(QQVf==5)
QQXe=(QQUf>=QQRf);else if(QQVf==6)
QQXe=(QQUf.indexOf(QQRf)>-1);else if(QQVf==7)
QQXe=(QQUf.indexOf(QQRf)<0);else if(QQVf==8)
{QQXe=QQUf.substr(0,QQRf.length)==QQRf;}else if(QQVf==9)
{QQXe=((QQUf>=QQRf)&&(QQUf<=QQSf));}else if(QQVf==10)
QQXe=((QQUf<QQRf)||(QQUf>QQSf));}else
{QQXe=false;}if(QQPf==2)
QQKf[QQl]=QQXe;else
{if((QQXe&&(QQPf==1))||(!QQXe&&(QQPf==0)))
QQl=QQk;}}if(QQPf==2)
QQXe=QQnE(QQQf,QQKf);QQXe=QQAf>0?!QQXe:QQXe;if((QQXe?1:0)==QQUe)
return QQUe;QQeE[QQVe]=QQXe;return 2;}function QQpE(QQZf,QQAg)
{var QQOe=new Date();var QQPe=new Date();QQPe.setTime(QQOe-0+parseInt(Ads_T[9],10));var QQBg=QQPe.getHours()*60+QQPe.getMinutes();if(QQZf<QQAg)
QQXe=((QQBg>=QQZf)&&(QQBg<=QQAg));else
QQXe=((QQBg>=QQZf)||(QQBg<=QQAg));return QQXe;}function QQqE(QQCg,QQDg)
{var QQk=QQCg.length;var QQEg;try
{if(typeof(QQCg.Ads_klist)=='string')
QQDg+=QQCg.Ads_klist+'#';}catch(objError) {}for(QQEg=0;QQEg<QQk;QQEg++)
{try
{QQDg=QQqE(QQCg.frames[QQEg],QQDg);}catch(objError) {}}return QQDg;}function QQrE(QQLd,QQE,QQCb,QQWe,QQFg)
{var QQUe=QQLd[0];var QQAf=QQLd[1];var QQXe,QQGg,QQHg,QQIg,QQJg,QQMe,QQKe,QQLe,QQl,QQKg,QQLg,QQMg,QQNg;QQeE=[true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true];if(QQLd.length==0)
return true;if(((QQUe>0)||(QQE==1))&&!((QQUe==1)&&(QQLd[2]==0)&&(QQLd[3]==1439)))
{QQXe=QQpE(QQLd[2],QQLd[3]);if((QQXe?1:0)==QQUe)
return QQXe;QQeE[0]=QQXe;}QQGg=QQjE(1,QQLd[4],QQCb,(QQE==0)?2:9,QQUe,1,QQWe);if(QQGg<2)
return QQGg==1;if(QQE==0)
{QQGg=QQjE(QQLd[22]&1,IAS[4],Ads_wid,7,QQUe,12,QQWe);if(QQGg<2)
return QQGg==1;QQGg=QQjE(QQLd[22]&2,IAS[6],Ads_nid,8,QQUe,13,QQWe);if(QQGg<2)
return QQGg==1;QQGg=QQlE(QQLd[22]&4,IAS[17],KAS[QQFg][13],12,QQUe,17,QQWe);if(QQGg<2)
return QQGg==1;}QQGg=QQkE(QQLd[6],Ads_T[0],QQAf&1,QQUe,2);if(QQGg<2)
return QQGg==1;QQGg=QQkE(QQLd[7],Ads_T[1],QQAf&2,QQUe,3);if(QQGg<2)
return QQGg==1;QQGg=QQkE(QQLd[8],Ads_T[2],QQAf&4,QQUe,4);if(QQGg<2)
return QQGg==1;QQGg=QQkE(QQLd[9],Ads_T[3],QQAf&8,QQUe,5);if(QQGg<2)
return QQGg==1;QQGg=QQkE(QQLd[26],Ads_T[12],QQAf&1024,QQUe,16);if(QQGg<2)
return QQGg==1;if(QQLd[10].length>1)
{QQXe=((QQLd[10].indexOf('#'+Ads_T[4]+'#')!=-1)||(QQLd[10].indexOf('#%'+Ads_T[10]+'#')!=-1)||(QQLd[10].indexOf('#$'+Ads_T[11]+'#')!=-1));if((Ads_nid==7)&&(Ads_T[4]<1)&&(QQLd[10].indexOf('#$14658#')!=-1)) QQXe=true;QQXe=(QQAf&16)>0?!QQXe:QQXe;if((QQXe?1:0)==QQUe)
return QQUe;QQeE[6]=QQXe;}QQGg=QQmE(QQLd[11],QQAf&32,QQUe,false,7);if(QQGg<2)
return QQGg==1;QQGg=QQmE(QQLd[12],QQAf&64,QQUe,true,8);if(QQGg<2)
return QQGg==1;if(QQLd[13].length>0)
{QQGg=QQoE(QQLd[13],';'+Ads_prf+';',QQAf&128,QQLd[15],QQLd[17],QQUe,9);if(QQGg<2)
return QQGg==1;}if(QQLd[14].length>0)
{QQiE();QQGg=QQoE(QQLd[14],QQdE,QQAf&256,QQLd[16],QQLd[18],QQUe,10);if(QQGg<2)
return QQGg==1;}intBwdLevel=0;intBwdTyp=QQLd[27];intBwdUser=QQwE[10];intBwdIP=Ads_T[13];if (intBwdTyp==1){QQsE();intBwdLevel=intBwdUser;}if (intBwdTyp==2){intBwdLevel=intBwdIP;}if (intBwdTyp==3){QQsE();intBwdLevel=((intBwdIP>intBwdUser)&&(intBwdUser!=0))?intBwdUser:(intBwdIP!=0)?intBwdIP:intBwdUser;}if (intBwdTyp==4){QQsE();intBwdLevel=(intBwdIP>intBwdUser)?intBwdIP:intBwdUser;}if((intBwdTyp==5)&&(intBwdUser==intBwdIP))
{ QQsE();intBwdLevel=intBwdIP;}QQGg=QQkE(QQLd[28],intBwdLevel,QQAf&512,QQUe,11);if(QQGg<2)
return QQGg==1;QQNg=QQLd[23];if((QQE==0)&&(QQNg>0))
{QQMe=QQLd[24];if(QQMe.length>2)
QQMe=QQMe.substring(1,QQMe.length-1);QQKe=QQMe.split('#');QQLe=QQKe.length;QQKg=-1;strKList='#'+QQqE(top,'');for(QQl=0;(QQl<QQLe)&&(QQKg<0);QQl++)
{QQLg=(strKList.indexOf('#'+QQKe[QQl]+'#')>-1);if((QQLg?1:4)==QQNg)
QQKg=0;if((QQLg?3:2)==QQNg)
QQKg=1;}if(QQKg<0)
QQKg=((QQNg==1)||(QQNg==4))?1:0;if(QQKg==QQUe)
return (QQKg==1);QQeE[14]=(QQKg==1);}QQl=QQLd[25];if(QQl>0)
{QQLg=IAS[8].indexOf('#'+QQl+':');if(QQLg!=-1)
{QQLg=IAS[8].indexOf(':',QQLg);QQMg=IAS[8].indexOf('#',QQLg);QQLg=IAS[8].substring(QQLg+1,QQMg);QQMg=Ads_fcount[QQl];if(typeOf(QQMg)=='undefined')
QQMg=0;QQXe=QQLg>QQMg;if((QQXe?1:0)==QQUe)
return QQXe;QQeE[15]=QQXe;}}if(QQUe!=2)
return (QQUe==0);else
{return QQnE(QQLd[19],QQeE);}}function QQsE()
{if((QQfE==0)&&QQzA&&(document.cookie.toLowerCase().indexOf('bndlvl')==-1))
QQfE=1;}function QQtE()
{if(QQfE!=1)
return;if(QQsD(1)<6||QQpB)
{if (QQpB||!navigator.javaEnabled())
{QQpD(1,'Start BW-Test','JavaScript');QQfE=3;QQvE();}else
{QQpD(1,'Start BW-Test','Java');document.write('<applet codebase="'+QQjB[Ads_sec]+'/" code="bandwidth.class" id="bandwidth" name="bandwidth" width="0" height="0" mayscript="MAYSCRIPT"><param name="cbfunc" value="QQuE"></applet>');QQfE=2;}}else
{QQpD(1,'Start BW-Test','Flash: '+QQsD(1));var QQWb=window.location.hostname;document.write('<scr'+'ipt for="Ads_BWD" event="FSCommand(QQPg,QQQg)" language="VBScript"> \n on error resume next \n call Ads_BWD_DoFSCommand(QQPg,QQQg) \n </scr'+'ipt\>');document.write('<object id="Ads_BWD" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab" width="1" height="1">');document.write('<param name=movie value="'+QQjB[Ads_sec]+'/dat/dlv/bwdetect.swf?domain='+QQWb+'&path='+QQjB[Ads_sec]+'"><param name=play value=true><param name=autoplay value=true>');document.write('<embed name="Ads_BWD" id="Ads_BWD" src="'+QQjB[Ads_sec]+'/dat/dlv/bwdetect.swf?domain='+QQWb+'&path='+QQjB[Ads_sec]+'" play=true autoplay=true swLiveConnect=true width="1" height="1" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash">');document.write('</embed></object>');QQfE=2;}}function QQuE(QQOg)
{QQdB=0;QQOg*=8;if(QQOg==0)
QQdB=0;else if(QQOg<9)
QQdB=1;else if(QQOg<33)
QQdB=2;else if(QQOg<65)
QQdB=3;else if(QQOg<129)
QQdB=4;else if(QQOg<385)
QQdB=5;else if(QQOg<769)
QQdB=6;else if(QQOg<1501)
QQdB=7;else if(QQOg<3001)
QQdB=8;else
QQdB=9;document.cookie='BNDLVL='+QQdB+QQfD(60*24*7);}function Ads_BWD_DoFSCommand(QQPg,QQQg)
{QQuE(QQQg/8);}function QQvE()
{var QQRg=new Date();document.writeln('<scr'+'ipt language="Javascript"><!--');document.writeln('QQcB=new Date();');document.writeln('/'+'/--></scr'+'ipt>');QQbD(QQjB[Ads_sec]+'/dat/dlv/aslprebwd.js?'+QQRg.getTime()+'0');}function Ads_PreBandwidth()
{var QQSg=new Date();var QQTg=Math.round((8026/((QQSg.getTime()-QQcB.getTime()+1)/1000))/1024);QQuE(QQTg);if (QQfE!=3)
QQrC();}